model_list:
  - model_name: llama3
    litellm_params:
      model: ollama/llama3
      api_base: http://localhost:11434
  - model_name: llama3:8b-vision
    litellm_params:
      model: ollama/llama3:8b-vision
      api_base: http://localhost:11434

general_settings:
  port: 8000
  num_workers: 4
